runtime: python
env: flex
entrypoint: gunicorn -b :$PORT wishlist.wsgi

beta_settings:
  cloud_sql_instances: [YOUR CONNECTION STRING HERE]

runtime_config:
  python_version: 3

env_variables:
  WISHLIST_DB_PW: [YOUR DB USER PASSWORD HERE]
  SECRET_KEY: [YOUR KEY HERE]
